# File: Generate-IdOverview.ps1

# Set the root documentation directory
$docsRoot = "."

# Output file
$idOverviewPath = Join-Path $docsRoot "IdOverview.md"

# Helper: Extract IDs and descriptions from a markdown file
function Get-IdTableRowsFromFile {
    param (
        [string]$FilePath,
        [string]$IdPattern,
        [string]$DescriptionPattern = "^\s*\|\s*([^\|]+)\s*\|\s*([^\|]+)\s*\|"
    )
    $rows = @()
    $seenIds = @{}
    if (Test-Path $FilePath) {
        $lines = Get-Content $FilePath
        foreach ($line in $lines) {
            if ($line -match $IdPattern) {
                if ($line -match $DescriptionPattern) {
                    $id = $matches[1].Trim()
                    $desc = $matches[2].Trim()
                    if (-not $seenIds.ContainsKey($id) -and $desc) {
                        $rows += "| $id | $desc | [Link to Doc][${id}-Doc] |"
                        $seenIds[$id] = $true
                    }
                }
            }
        }
    }
    return $rows
}

# Helper: Extract all link lines starting with an ID from a file
function Get-IdLinksFromFile {
    param (
        [string]$FilePath
    )
    $idLinks = @()
    if (Test-Path $FilePath) {
        $lines = Get-Content $FilePath
        foreach ($line in $lines) {
            if ($line -match '^\[[A-Za-z0-9\-]+\]:') {
                $idLinks += $line
            }
        }
    }
    return $idLinks
}

# Collect Use Cases
$useCaseRows = @()
$useCaseDirs = Get-ChildItem -Path "$docsRoot/UseCases" -Directory -ErrorAction SilentlyContinue
foreach ($dir in $useCaseDirs) {
    $readme = Join-Path $dir.FullName "README.md"
    if (Test-Path $readme) {
        $rows = Get-IdTableRowsFromFile -FilePath $readme -IdPattern "^UC-\d+"
        if ($rows) { $useCaseRows += $rows }
    }
}

# Collect KPIs
$kpiFile = "$docsRoot\KPI.md"
$kpiRows = Get-IdTableRowsFromFile -FilePath $kpiFile -IdPattern "KPI-(FR|NFR)-\d+"

# Collect Quality Criteria
$qcFile = "$docsRoot\QualityCriteriaCode.md"
$qcRows = Get-IdTableRowsFromFile -FilePath $qcFile -IdPattern "QC-\d+"

# Collect Risk Analysis
$riskFile = "$docsRoot\RiskAnalysis.md"
$riskRows = Get-IdTableRowsFromFile -FilePath $riskFile -IdPattern "RISK-\d+"

# Collect ERD, DomainModel, DCD
$erdFile = "$docsRoot\ERD.md"
$erdRows = Get-IdTableRowsFromFile -FilePath $erdFile -IdPattern "ERD-\d+"
$domainFile = "$docsRoot\DomainModel.md"
$domainRows = Get-IdTableRowsFromFile -FilePath $domainFile -IdPattern "DM-\d+"
$dcdFile = "$docsRoot\DCD.md"
$dcdRows = Get-IdTableRowsFromFile -FilePath $dcdFile -IdPattern "DCD-\d+"

# Gather all ID links from relevant files
$idLinksRaw = @()
$idLinksRaw += Get-IdLinksFromFile -FilePath $kpiFile
$idLinksRaw += Get-IdLinksFromFile -FilePath $qcFile
$idLinksRaw += Get-IdLinksFromFile -FilePath $riskFile
$idLinksRaw += Get-IdLinksFromFile -FilePath $erdFile
$idLinksRaw += Get-IdLinksFromFile -FilePath $domainFile
$idLinksRaw += Get-IdLinksFromFile -FilePath $dcdFile

# Collect all IDs used in the tables
$allTableIds = @()
foreach ($row in $useCaseRows + $kpiRows + $qcRows + $riskRows + $erdRows + $domainRows + $dcdRows) {
    if ($row -match '^\|\s*([^\|]+)\s*\|') {
        $allTableIds += $matches[1].Trim()
    }
}
$allTableIds = $allTableIds | Sort-Object -Unique

# Filter idLinks to only those present in the tables
$idLinks = @()
foreach ($link in $idLinksRaw) {
    if ($link -match '^\[([^\]]+)\]:') {
        $id = $matches[1]
        if ($allTableIds -contains $id) {
            $idLinks += $link
        }
    }
}

# Write IdOverview.md with UTF8 and CRLF
$content = @"
<!--
    This file is auto-generated by Generate-IdOverview.ps1.
    Do not edit this file directly. Instead, modify the source documentation files.
    Run the script to regenerate this file.
-->
# Id Overview

The `Id` property is a unique identifier used in various contexts within software development, particularly in project files and configurations. It serves as a way to distinctly identify red lines from documentation to code.

## Use Case

| **ID** | **Description** | Cross Reference links |
|--------|-----------------|----------------------|
$($useCaseRows -join "`n")

## ID for KPIs

| **ID** | **Description** | Cross Reference links |
|--------|-----------------|----------------------|
$($kpiRows -join "`n")

## Quality Criteria

| **ID** | **Description** | Cross Reference links |
|--------|-----------------|----------------------|
$($qcRows -join "`n")

## Risk Analysis

| **ID** | **Description** | Cross Reference links |
|--------|-----------------|----------------------|
$($riskRows -join "`n")

## ERD

| **ID** | **Description** | Cross Reference links |
|--------|-----------------|----------------------|
$($erdRows -join "`n")

## Domain Model

| **ID** | **Description** | Cross Reference links |
|--------|-----------------|----------------------|
$($domainRows -join "`n")

## DCD

| **ID** | **Description** | Cross Reference links |
|--------|-----------------|----------------------|
$($dcdRows -join "`n")

<!-- Links to related information -->
$($idLinks -join "`r`n")
"@

# Convert to CRLF endings
$content = $content -replace "`r?`n", "`r`n"

# Save with UTF8 (no BOM) and CRLF
[System.IO.File]::WriteAllText($idOverviewPath, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host "IdOverview.md generated at $idOverviewPath with UTF8 and CRLF endings."